{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'css': [],
    'data': [   'data/cronjobs.xml',
                'data/datapolice.xml',
                'views/fetchmail_server_form.xml',
                'views/missing_entry_form.xml',
                'views/missing_entry_tree.xml',
                'views/missing_search.xml',
                'views/menu.xml',
                'security/ir.model.access.csv'],
    'demo': [],
    'depends': ['datapolice', 'fetchmail', 'mail'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'mail_check_missed_to_fetch',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
