{   'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'css': [],
    'data': [],
    'demo': [],
    'depends': ['mail'],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'mail_notifications_in_queue',
    'qweb': [],
    'test': [],
    'version': '13.0.1.0'}
